Update terraform-plan.yml

diff --git a/.github/workflows/terraform-plan.yml b/.github/workflows/terraform-plan.yml
--- a/.github/workflows/terraform-plan.yml
+++ b/.github/workflows/terraform-plan.yml
@@ -3,11 +3,9 @@ on:
   pull_request:
     branches:
       - prod
-
 permissions:
   pull-requests: write
   contents: read
-
 jobs:
   terraform-plan:
     runs-on: ubuntu-latest
@@ -34,10 +32,23 @@ jobs:
         id: plan
         run: |
           cd enviroments/prod
-          terraform plan -no-color > plan.txt
+          # Capture the plan output but don't save it for later execution
+          terraform plan -input=false -no-color -detailed-exitcode > plan.txt || exit_code=$?
+          
+          # Add plan output to GitHub env
           echo "PLAN<<EOF" >> $GITHUB_ENV
           cat plan.txt >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
+
+          # Check if changes are present
+          if [ $exit_code -eq 2 ]; then
+            echo "Changes detected in plan"
+          elif [ $exit_code -eq 0 ]; then
+            echo "No changes detected in plan"
+          else
+            echo "Error during plan"
+            exit 1
+          fi
 
       - name: Add Plan Comment
         uses: actions/github-script@v6
@@ -54,7 +65,6 @@ jobs:
             \`\`\`
 
             </details>`;
-
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
