Update terraform-plan.yml

diff --git a/.github/workflows/terraform-plan.yml b/.github/workflows/terraform-plan.yml
--- a/.github/workflows/terraform-plan.yml
+++ b/.github/workflows/terraform-plan.yml
@@ -35,26 +35,29 @@ jobs:
         id: plan
         run: |
           cd enviroments/prod
-          # Initialize exit_code
-          exit_code=0
-          
-          # Capture the plan output but don't save it for later execution
-          terraform plan -input=false -no-color -detailed-exitcode > plan.txt || exit_code=$?
-          
+
+          # Create plan.txt and capture both output and exit code
+          terraform plan -input=false -no-color -detailed-exitcode > plan.txt 2>&1
+          TERRAFORM_EXIT_CODE=$?
+
           # Add plan output to GitHub env
           echo "PLAN<<EOF" >> $GITHUB_ENV
           cat plan.txt >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
-          
-          # Check if changes are present
-          if [ "$exit_code" -eq 2 ]; then
-            echo "Changes detected in plan"
-          elif [ "$exit_code" -eq 0 ]; then
-            echo "No changes detected in plan"
-          else
-            echo "Error during plan"
-            exit 1
-          fi
+
+          # Check terraform exit code
+          case $TERRAFORM_EXIT_CODE in
+            0)
+              echo "No changes detected in plan"
+              ;;
+            2)
+              echo "Changes detected in plan"
+              ;;
+            *)
+              echo "Error during plan"
+              exit 1
+              ;;
+          esac
 
       - name: Add Plan Comment
         uses: actions/github-script@v6
